PAGE_SIZE: 10
TEXT: "text"
KEY_TEXT: "1"
ACCEPT: "accept"
WAITING: "waiting"
TIME_DEFAUT: "00:00:00"
WITH_10_MINUTES: 10
WITH_20_MINUTES: 20
DATE_FORMAT: "%d/%m/%Y"
TIME_FORMAT: "%H:%M:%S"
STATUS_TESTING: "testing"
STATUS_UNCHECKED: "unchecked"
STATUS_CHECKED: "checked"
FINISH: "Finish"
STATUS_CHECKED: 3
